# Generated by Django 3.2.10 on 2022-01-13 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['team'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('execution_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team'],
            },
        ),
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('STOPPED', 'Stopped')], default='READY', max_length=50)),
                ('execute_for', models.CharField(choices=[('FILTERS', 'Filters'), ('LIST', 'List'), ('ALL', 'All')], max_length=20)),
                ('execution_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('API', 'Api')], max_length=20)),
                ('inbound_start_message', models.TextField(blank=True, null=True)),
                ('inbound_start_message_match_exact', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.flow')),
            ],
            options={
                'ordering': ['flow', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FlowExecutionContact',
            fields=[
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('STOPPED', 'Stopped'), ('EXPIRED', 'Expired')], default='READY', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_executions', to='api.contact')),
                ('flow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_executions', to='api.flowexecution')),
            ],
            options={
                'ordering': ['flow_execution', 'created_on'],
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('name', models.CharField(max_length=100)),
                ('step_type', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('LOCATION', 'Location')], max_length=20, null=True)),
                ('answer_type', models.CharField(blank=True, choices=[('FREE_TEXT', 'Free Text'), ('SINGLE_OPTION', 'Single Option'), ('MULTIPLE_OPTIONS', 'Multiple Options'), ('NUMBER', 'Number'), ('URL', 'Url'), ('EMAIL', 'Email'), ('FILE', 'File'), ('IMAGE', 'Image'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Datetime'), ('BOOL', 'Bool')], max_length=30, null=True)),
                ('answer_validation_message', models.TextField(blank=True, null=True)),
                ('answer_options', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.flow')),
                ('next_step_alternate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_step_alt', to='api.flowstep')),
                ('next_step_default', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_step', to='api.flowstep')),
            ],
            options={
                'ordering': ['flow', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepConditionalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('comparison', models.CharField(choices=[('exact', 'Exact'), ('!exact', 'Different'), ('gte', 'Gte'), ('gt', 'Gt'), ('lte', 'Lte'), ('lt', 'Lt'), ('isnull', 'Is Null'), ('!isnull', 'Not Null'), ('icontains', 'Contains'), ('!icontains', 'Not Contains')], max_length=30)),
                ('value', models.CharField(max_length=255)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='api.flowstep')),
            ],
        ),
        migrations.CreateModel(
            name='FlowExecutionStep',
            fields=[
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creado el')),
                ('last_updated_on', models.DateTimeField(auto_now=True, verbose_name='Última actualización el')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING_TO_START', 'Waiting To Start'), ('NOT_EXECUTED', 'Not Executed'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='WAITING_TO_START', max_length=20)),
                ('execution_result', models.JSONField(blank=True, null=True)),
                ('flow_execution_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_steps', to='api.flowexecutioncontact')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_steps', to='api.flowstep')),
            ],
            options={
                'ordering': ['flow_execution_contact', 'created_on'],
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='first_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ffs', to='api.flowstep'),
        ),
        migrations.AddField(
            model_name='flow',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='api.team'),
        ),
        migrations.AddField(
            model_name='contact',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.team'),
        ),
    ]
