# Generated by Django 4.0.2 on 2022-02-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='execution_type',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='flowexecution',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flowexecution',
            name='execute_for',
        ),
        migrations.RemoveField(
            model_name='flowexecution',
            name='execution_type',
        ),
        migrations.RemoveField(
            model_name='flowexecution',
            name='inbound_start_message',
        ),
        migrations.RemoveField(
            model_name='flowexecution',
            name='inbound_start_message_match_exact',
        ),
        migrations.RemoveField(
            model_name='flowexecution',
            name='start_on',
        ),
    ]
