# Generated by Django 4.0.2 on 2022-02-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_flow_created_by_remove_flow_execution_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowexecution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flowexecutioncontact',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flowexecutionstep',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flowstep',
            name='answer_options',
        ),
        migrations.RemoveField(
            model_name='flowstep',
            name='answer_validation_message',
        ),
        migrations.RemoveField(
            model_name='flowstep',
            name='body_type',
        ),
        migrations.AlterField(
            model_name='flowstep',
            name='step_type',
            field=models.CharField(choices=[('CONDITIONAL', 'Conditional'), ('MESSAGE', 'Message'), ('QUESTION', 'Question')], max_length=100),
        ),
        migrations.DeleteModel(
            name='StepConditionalCondition',
        ),
    ]
